### ISSUE TITLE
能否将public里的资源文件隐藏

### ISSUE THREAD

**Issue by Coolkkmeat** [Aunger-ops/phalapi-theme-magician#1]
如题，比如使用Github Pages，或者将这些文件放入src/view/docs里。感觉放到public有点复杂。
感谢。

**Comment by Aunger-ops** [comment]
原生文档模板也是放public，感觉不支持这么改，而且这样好像没必要，直接复制粘贴即可

**Comment by Aunger-ops** [comment]
如果可以这么改可以提PR
